package com.discount.mgt.domain;

/**
 * @author Nava Krishna
 *
 */
interface DBColumns {

    String CUSTOMER_ID_COLUMN = "CUSTOMER_ID";
    String CUSTOMERTYPE_COLUMN = "CUSTOMER_TYPE";
    String PRODUCT_ID_COLUMN = "PRODUCT_ID";
    String PRODUCTNAME_COLUMN = "PRODUCT_NAME";
    String PRODUCTTYPE_COLUMN = "PRODUCT_TYPE";
    String PRICE_COLUMN = "PRICE";
    String PRODUCT_CREATE_DATE = "SALES_DATE";
    String DISCOUNT_TYPE_COLUMN = "DISCOUNT_TYPE";
    String PROMOTION_STATUS_COULUM = "PROMOTION_STATUS";
    String PRODUCTDIVISION_COLUMN = "PRODUCT_DIVISION";
    String DISCOUNT_COLUMN="DISCOUNT";
    String DISCOUNT_MONTH_COLUMN= "DISCOUNT_MONTH";
}
